[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
proxa = "6LAR9TGXRnsLVtc4MibivdgNgqWGpiXMsR64p21VCRDZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["."]

[scripts]
test = "../../node_modules/.bin/tsc -p tsconfig.json --outDir .test-build && ../../node_modules/.bin/mocha -t 1000000 \".test-build/**/*.js\""
